inherit_from: .rubocop_todo.yml

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false
