inherit_from: .rubocop_todo.yml

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Metrics/AbcSize:
  Max: 24

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*_spec.rb'

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
